<?php

namespace Soipo\Okento\UserBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByUsernameOrEmail($username){

        $query = $this->createQueryBuilder('u')
                    ->where('u.username = :username')
                    ->orWhere('u.email = :username')
                    ->setParameter('username',$username)
                    ->getQuery();
                ;
       return $query->getOneOrNullResult();
    }
}
